version: '3'
services:
  back:
    build: ./back
    container_name: back
    ports:
      - "8080:80"
  postgresql-server:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: POSTGRES_DB
    ports:
      - "5433:5432"
  front:
    build: ./front
    container_name: front
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./front/gallerywebapp/src:/app/src